config/routes.rb
Rails.application.routes.draw do
  root to: 'welcome#index'

  resources :games

  #TODO when we get to roles and logins, we need
  #an admin namespace where we deactivate players, as opposed
  #to destroying them.
  
  resources :players, except: :destroy
end

app/models/game.rb
class Game < ActiveRecord::Base
  after_save :process_score
  
  #TODO move away from hardcoding players 1 and 2
  #TODO Use a join table like GamePlayer to relate player and game

  [:player_1_score, :player_2_score].each do |attribute|
    validates attribute, presence: true
    validates attribute, numericality: {only_integer: true}
  end

  validate :check_players_are_not_the_same

  belongs_to :player_1, class_name: 'Player', foreign_key: 'player_1_id', required: true
  belongs_to :player_2, class_name: 'Player', foreign_key: 'player_2_id', required: true

    def winner
      return nil if tie_game?
      (player_1_score > player_2_score) ? player_1 : player_2
    end

    def tie_game?
      player_1_score == player_2_score
    end

    def player_1_winner?
      return false if tie_game?
      (player_1_score > player_2_score)
    end

    def player_2_winner?
      return false if tie_game?
      not player_1_winner?
    end

  private

    def check_players_are_not_the_same
      # a rare example of me expanding to three lines if one would be too long
      if player_1_id == player_2_id
        errors.add(:player_1_id, "Cannot use same player twice")
      end
    end

    def process_score
      GameRatingsCalculator.new.score_game(self)
    end

end

app/models/player.rb
class Player < ActiveRecord::Base

  VALID_HANDS = ["Right", "Left"]

  [:name, :email, :hand, :grade].each do |attribute|
    validates attribute, presence: true
  end

  validates :hand, inclusion: { in: VALID_HANDS,
    message: "%{value} is not a valid hand" }
  validates :grade, numericality: { only_integer: true }
  validates :email, format: { with: /\A([^@\s]+)@((?:[-a-z0-9]+\.)+[a-z]{2,})\z/i }

end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  protect_from_forgery with: :exception
end

app/controllers/games_controller.rb
class GamesController < ApplicationController
  before_action :set_game, only: [:show, :edit, :update, :destroy]

 def index
   @games = Game.all.includes(:player_1, :player_2)
 end

 def show
 end

 def new
   @game = Game.new
 end

 def edit
 end

 def create
   @game = Game.new(game_params)

   respond_to do |format|
     if @game.save
       format.html { redirect_to @game, notice: 'Game was successfully created.' }
       format.json { render :show, status: :created, location: @game }
     else
       format.html { render :new }
       format.json { render json: @game.errors, status: :unprocessable_entity }
     end
   end
 end

 def update
   respond_to do |format|
     if @game.update(game_params)
       format.html { redirect_to @game, notice: 'Game was successfully updated.' }
       format.json { render :show, status: :ok, location: @game }
     else
       format.html { render :edit }
       format.json { render json: @game.errors, status: :unprocessable_entity }
     end
   end
 end

 def destroy
   @game.destroy
   respond_to do |format|
     format.html { redirect_to games_url, notice: 'Game was successfully destroyed.' }
     format.json { head :no_content }
   end
 end

 private
   def set_game
     @game = Game.find(params[:id])
   end

   def game_params
     params.fetch(:game, {}).permit(:player_1_id, :player_2_id, :player_1_score, :player_2_score)
   end

end

app/controllers/players_controller.rb
class PlayersController < ApplicationController
  before_action :set_player, only: [:show, :edit, :update, :destroy]

def index
  @players = Player.all.order(grade: :desc)
end

def show
end

def new
  @player = Player.new
end

def edit
end

def create
  @player = Player.new(player_params)

  respond_to do |format|
    if @player.save
      format.html { redirect_to @player, notice: 'Player was successfully created.' }
      format.json { render :show, status: :created, location: @player }
    else
      format.html { render :new }
      format.json { render json: @player.errors, status: :unprocessable_entity }
    end
  end
end

def update
  respond_to do |format|
    if @player.update(player_params)
      format.html { redirect_to @player, notice: 'Player was successfully updated.' }
      format.json { render :show, status: :ok, location: @player }
    else
      format.html { render :edit }
      format.json { render json: @player.errors, status: :unprocessable_entity }
    end
  end
end

private
  def set_player
    @player = Player.find(params[:id])
  end

  def player_params
    params.require(:player).permit(:name, :email, :hand, :grade)
  end
end

app/controllers/welcome_controller.rb
class WelcomeController < ApplicationController
  def index
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/views/games/_form.html.erb
<%= form_for @game do |f| %>
  <div class="row">
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :player_1_id, :class => 'control-label' %>
        <%= f.collection_select :player_1_id, Player.all, :id, :name, {}, {class: 'form-control'} %>
      </div>
      <div class="form-group">
        <%= f.label :player_2_id, :class => 'control-label' %>
        <%= f.collection_select :player_2_id, Player.all, :id, :name, {}, {class: 'form-control'} %>
      </div>
    </div>
    <div class="col-md-6">
      <div class="form-group">
        <%= f.label :player_1_score, class: 'control-label' %>
        <%= f.text_field :player_1_score, type: "number",  min: "0", class: 'form-control' %>
      </div>
      <div class="form-group">
        <%= f.label :player_2_score, class: 'control-label' %>
        <%= f.text_field :player_2_score, type: "number",  min: "0", class: 'form-control' %>
      </div>
    </div>
  </div>
  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                games_path, :class => 'btn' %>
  </div>
<% end %>

app/views/games/edit.html.erb
<%- model_class = Game -%>
<div class='col-md-6'>
  <div class="page-header">
    <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                     :default => "Edit #{model_class.model_name.human}") %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/games/index.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <div class='col-md-10'>
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  </div>
  <div class='col-md-2'>
    <%= link_to "Home", :root, style: 'vertical-align: middle', class: 'btn btn-primary btn-lg pull-right' %>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:id) %></th>
      <th>Player 1</th>
      <th>Player 2</th>
      <th><%= model_class.human_attribute_name(:player_1_score) %></th>
      <th><%= model_class.human_attribute_name(:player_2_score) %></th>
      <th><%= model_class.human_attribute_name(:created_at) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @games.each do |game| %>
      <tr>
        <td><%= link_to game.id, game_path(game) %></td>
        <td class="<%='winner' if game.player_1_winner?%>">
            <%= game.player_1.name %>
        </td>
        <td class="<%='winner' if game.player_2_winner?%>">
            <%= game.player_2.name %>
        </td>
        <td><%= game.player_1_score %></td>
        <td><%= game.player_2_score %></td>
        <td><%=l game.created_at %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_game_path(game), :class => 'btn btn-primary btn-xs' %>
          <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
                      game_path(game),
                      :method => :delete,
                      :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
                      :class => 'btn btn-danger btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_game_path,
            :class => 'btn btn-primary' %>

app/views/games/new.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/games/show.html.erb
<%- model_class = Game -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong>Player 1:</strong></dt>
  <dd><%= @game.player_1.name %></dd>
  <dt><strong>Player 2:</strong></dt>
  <dd><%= @game.player_2.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:player_1_score) %>:</strong></dt>
  <dd><%= @game.player_1_score %></dd>
  <dt><strong><%= model_class.human_attribute_name(:player_2_score) %>:</strong></dt>
  <dd><%= @game.player_2_score %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              games_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_game_path(@game), :class => 'btn btn-primary' %>
  <%= link_to t('.destroy', :default => t("helpers.links.destroy")),
              game_path(@game),
              :method => 'delete',
              :data => { :confirm => t('.confirm', :default => t("helpers.links.confirm", :default => 'Are you sure?')) },
              :class => 'btn btn-danger' %>
</div>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>RailsPingPong</title>
  <%= stylesheet_link_tag    'application', media: 'all' %>
  <%= javascript_include_tag 'application' %>
  <%= csrf_meta_tags %>
</head>
<body>
<div class="container">
  <%= yield %>
</div>
</body>
</html>

app/views/players/_form.html.erb
<%= bootstrap_form_for @player do |f| %>
  <div class="form-group">
    <%= f.text_field :name %>
  </div>
  <div class="form-group">
    <%= f.email_field :email %>
  </div>
  <div class="form-group">
    <%= f.select :hand, Player::VALID_HANDS%>
  </div>
  <div class="form-group">
    <%= f.text_field :grade, type: "number",  min: "0", max: "100" %>
  </div>

  <div class="form-actions">
    <%= f.submit nil, :class => 'btn btn-primary' %>
    <%= link_to t('.cancel', :default => t("helpers.links.cancel")),
                players_path, :class => 'btn' %>
  </div>
<% end %>

app/views/players/edit.html.erb
<%- model_class = Player -%>
<div class='col-md-6'>
  <div class="page-header">
    <h1><%=t '.title', :default => t('helpers.titles.edit', :model => model_class.model_name.human,
                                     :default => "Edit #{model_class.model_name.human}") %></h1>
  </div>
  <%= render :partial => 'form' %>
</div>

app/views/players/index.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <div class='col-md-10'>
    <h1><%=t '.title', :default => model_class.model_name.human.pluralize %></h1>
  </div>
  <div class='col-md-2'>
    <%= link_to "Home", :root, style: 'vertical-align: middle', class: 'btn btn-primary btn-lg pull-right' %>
  </div>
</div>
<table class="table table-striped">
  <thead>
    <tr>
      <th><%= model_class.human_attribute_name(:name) %></th>
      <th><%= model_class.human_attribute_name(:email) %></th>
      <th><%= model_class.human_attribute_name(:hand) %></th>
      <th><%= model_class.human_attribute_name(:grade) %></th>
      <th><%=t '.actions', :default => t("helpers.actions") %></th>
    </tr>
  </thead>
  <tbody>
    <% @players.each do |player| %>
      <tr>
        <td><%= link_to player.name, player_path(player) %></td>
        <td><%= player.email %></td>
        <td><%= player.hand %></td>
        <td><%= player.grade %></td>
        <td>
          <%= link_to t('.edit', :default => t("helpers.links.edit")),
                      edit_player_path(player), :class => 'btn btn-primary btn-xs' %>
        </td>
      </tr>
    <% end %>
  </tbody>
</table>

<%= link_to t('.new', :default => t("helpers.links.new")),
            new_player_path,
            :class => 'btn btn-primary' %>

app/views/players/new.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => t('helpers.titles.new', :model => model_class.model_name.human,
                                 :default => "New #{model_class.model_name.human}") %></h1>
</div>
<%= render :partial => 'form' %>

app/views/players/show.html.erb
<%- model_class = Player -%>
<div class="page-header">
  <h1><%=t '.title', :default => model_class.model_name.human %></h1>
</div>

<dl class="dl-horizontal">
  <dt><strong><%= model_class.human_attribute_name(:name) %>:</strong></dt>
  <dd><%= @player.name %></dd>
  <dt><strong><%= model_class.human_attribute_name(:email) %>:</strong></dt>
  <dd><%= @player.email %></dd>
  <dt><strong><%= model_class.human_attribute_name(:hand) %>:</strong></dt>
  <dd><%= @player.hand %></dd>
  <dt><strong><%= model_class.human_attribute_name(:grade) %>:</strong></dt>
  <dd><%= @player.grade %></dd>
</dl>

<div class="form-actions">
  <%= link_to t('.back', :default => t("helpers.links.back")),
              players_path, :class => 'btn'  %>
  <%= link_to t('.edit', :default => t("helpers.links.edit")),
              edit_player_path(@player), :class => 'btn btn-primary' %>
</div>

app/views/welcome/index.html.erb
<div class="container">
  <div class="col-md-6 text-center">
    <p>
      <%= image_tag 'balls_of_fury.jpg' %>
    </p>
    <p class="bs-component container">
      <div class="row center-block">
        <%= link_to "Players", :players, class: 'btn btn-primary btn-lg' %>
      </div>
    </p>
    <p class="bs-component container">
      <div class="row center-block">
        <%= link_to "Games", :games, class: 'btn btn-primary btn-lg' %>
      </div>
    </p>
  </div>
  <div class="col-md-6 text-center">
    <%= image_tag 'intense_table_tennis.jpg' %>
  </div>
</div>